import authOptions from "@/app/api/auth/[...nextauth]/authOptions";
import  Navbar from "@/app/components/Navbar";
import  AuthSessionProvider from "@/app/components/AuthSessionProvider";
import { getServerSession } from "next-auth";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Playlist Analyzer',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <AuthSessionProvider session={session}>
        <body className={inter.className}><Navbar/>{children}</body>
      </AuthSessionProvider>
    </html>
  )
}
