import authOptions from "@/app/api/auth/[...nextauth]/authOptions";
import  AuthSessionProvider from "@/app/components/AuthSessionProvider";
import { getServerSession } from "next-auth";

import  Navbar from "@/app/components/Navbar";
import  Footer from "@/app/components/Footer";
import  Login from "@/app/components/Login";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Playlist Analyzer',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  

  return (
    <html lang="en" className="bg-black text-white">
      <AuthSessionProvider session={session}>
        <body className={inter.className}>
        {!session ? <Login /> :
          <>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </>
        }
        </body>
      </AuthSessionProvider>
    </html>
  )
}
